services:
  mongo:
    image: mongo
    container_name: campusfit-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: campusfit_user
      MONGO_INITDB_ROOT_PASSWORD: campusfit_password
    volumes:
      - campusfit-data:/data/db
    networks:
      - campusfit-network

  app:
    image: campusfit-app:v1
    container_name: campusfit-app-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      APP_ENV: docker-compose
      MONGO_URI: mongodb://campusfit_user:campusfit_password@mongo:27017/campusfit_db?authSource=admin
    depends_on:
      - mongo
    networks:
      - campusfit-network

volumes:
  campusfit-data:

networks:
  campusfit-network:
    driver: bridge
