apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusfit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campusfit-app
  template:
    metadata:
      labels:
        app: campusfit-app
    spec:
      containers:
      - name: campusfit-app
        image: prince46/campusfit-app:latest

        ports:
        - containerPort: 3000

        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT

        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

        - name: MONGO_URI
          value: mongodb://campusfit_user:campusfit_password@mongodb-service:27017/campusfit_db?authSource=admin

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
